apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deployment.yaml
  - base/service.yaml
  - base/configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: buildpacks-eks-eval
