apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse
  labels:
    app.kubernetes.io/name: pulse
    app.kubernetes.io/part-of: buildpacks-eks-eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulse
    spec:
      containers:
        - name: pulse
          image: ECR_URI:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: pulse-config
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
